### ISSUE TITLE
create basic form for posting and updating results

### ISSUE THREAD

**Issue by wa-rren-dev** [wa-rren-dev/a11y-cat#16]

**Comment by wa-rren-dev** [comment]
@garyburton could you add an input for updating the audit name once it’s saved?

**Comment by garyburton** [comment]
> @garyburton could you add an input for updating the audit name once it’s saved?

So on the same route? Swap the name input for an update name input?

**Comment by wa-rren-dev** [comment]
Yeah that'd be good. Just so we've got an example of a PUT or equivalent

**Comment by garyburton** [comment]
I'll do an edit route like `/audits/32j13kjk12/edit`

**Comment by garyburton** [comment]
That is done
